set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

# Start interactive Codex CLI
[arg("args", help="Arguments passed to Codex")]
run *args:
    @just exec "$(id -u):$(id -g)" codex {{args}}

# Open a shell inside Mipe container
[arg("user", help="User to run the shell as")]
shell user='root':
    @just exec {{user}} bash

# Run Docker Compose
[arg("args", help="Arguments passed to docker compose")]
compose *args:
    @LOCAL_UID=$(id -u) LOCAL_GID=$(id -g) \
        docker compose {{args}}

[private]
exec user *args:
    @just compose up -d
    @just compose exec \
            --user {{user}} \
            mipe \
            {{args}}
