services:
  mipe-java:
    image: mipe-codex:21-java
    build:
      context: .
      dockerfile: docker/java/Dockerfile

  mipe-node:
    image: mipe-codex:26-node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
